CREATE TABLE `m_form_generation_details` (
  `Form_Gen_Details_Id` int NOT NULL AUTO_INCREMENT,
  `Project_ID` int DEFAULT NULL,
  `Module_ID` int DEFAULT NULL,
  `Layout_ID` int DEFAULT NULL,
  `Product_ID` int DEFAULT NULL,
  `Page_Name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Purpose` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `C2C_CDATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `C2C_CUSER` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `C2C_UDATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `C2C_UUSER` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `C2C_STATUS` enum('active','inactive') COLLATE utf8mb4_unicode_ci DEFAULT 'active',
  `C2C_INACTIVE_REASON` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`Form_Gen_Details_Id`),
  KEY `fk_form_project` (`Project_ID`),
  KEY `fk_form_product` (`Product_ID`),
  KEY `fk_form_layout` (`Layout_ID`),
  KEY `fk_module_id` (`Module_ID`),
  CONSTRAINT `fk_form_layout` FOREIGN KEY (`Layout_ID`) REFERENCES `m_layout` (`Layout_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_form_product` FOREIGN KEY (`Product_ID`) REFERENCES `m_product` (`Product_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_form_project` FOREIGN KEY (`Project_ID`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_module_id` FOREIGN KEY (`Module_ID`) REFERENCES `modules` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `m_layout` (
  `Layout_ID` int NOT NULL AUTO_INCREMENT,
  `Project_ID` int DEFAULT NULL,
  `Layout_Name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `C2C_Cdate` datetime DEFAULT NULL,
  `C2C_Cuser` decimal(9,0) DEFAULT NULL,
  `C2C_Udate` datetime DEFAULT NULL,
  `C2C_Uuser` decimal(9,0) DEFAULT NULL,
  `C2C_Status` bit(1) DEFAULT NULL,
  `C2C_Inactive_Reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`Layout_ID`),
  KEY `fk_layout_project` (`Project_ID`),
  CONSTRAINT `fk_layout_project` FOREIGN KEY (`Project_ID`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `m_product` (
  `Product_ID` int NOT NULL AUTO_INCREMENT,
  `Project_ID` int DEFAULT NULL,
  `Product_Name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `C2C_Cdate` datetime DEFAULT NULL,
  `C2C_Cuser` decimal(9,0) DEFAULT NULL,
  `C2C_Udate` datetime DEFAULT NULL,
  `C2C_Uuser` decimal(9,0) DEFAULT NULL,
  `C2C_Status` bit(1) DEFAULT NULL,
  `C2C_Inactive_Reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`Product_ID`),
  KEY `fk_product_project` (`Project_ID`),
  CONSTRAINT `fk_product_project` FOREIGN KEY (`Project_ID`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `m_form_field_details` (
  `Form_Gen_Field_Details_Id` int NOT NULL AUTO_INCREMENT,
  `TAB_ID` int NOT NULL,
  `FIELD_SOURCE_LOV_DET_ID` int DEFAULT NULL,
  `FIELD_TYPE_ID` int DEFAULT NULL,
  `SP_NAME` varchar(255) DEFAULT NULL,
  `SP_PARAM` varchar(255) DEFAULT NULL,
  `TABLE_NAME` varchar(255) DEFAULT NULL,
  `TABLE_COLUMNS` varchar(255) DEFAULT NULL,
  `CUSTOM_NAME` varchar(255) DEFAULT NULL,
  `FIELD_NAME` varchar(100) NOT NULL,
  `FIELD_SIZE_LOV_DET_ID` int DEFAULT NULL,
  `FIELD_ICON_LOV_DET_ID` int DEFAULT NULL,
  `PLACEHOLDER` varchar(255) DEFAULT NULL,
  `FIELD_ORDER_LOV_DET_ID` int DEFAULT NULL,
  `STORING_SP` varchar(100) DEFAULT NULL,
  `EVENT_HANDLER_ID` int DEFAULT NULL,
  `STATUS` enum('active','inactive') DEFAULT 'active',
  `INACTIVE_REASON` varchar(255) DEFAULT NULL,
  `C2C_CDATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `C2C_CUSER` varchar(100) DEFAULT NULL,
  `C2C_UDATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `C2C_UUSER` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`Form_Gen_Field_Details_Id`),
  KEY `TAB_ID` (`TAB_ID`),
  KEY `FIELD_SOURCE_LOV_DET_ID` (`FIELD_SOURCE_LOV_DET_ID`),
  KEY `FIELD_SIZE_LOV_DET_ID` (`FIELD_SIZE_LOV_DET_ID`),
  KEY `FIELD_ICON_LOV_DET_ID` (`FIELD_ICON_LOV_DET_ID`),
  KEY `FIELD_ORDER_LOV_DET_ID` (`FIELD_ORDER_LOV_DET_ID`),
  KEY `FK_FIELD_TYPE` (`FIELD_TYPE_ID`),
  KEY `fk_add_form_event_handler` (`EVENT_HANDLER_ID`),
  CONSTRAINT `fk_add_form_event_handler` FOREIGN KEY (`EVENT_HANDLER_ID`) REFERENCES `form_event_handler_master` (`FORM_EVENT_HANDLER_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_FIELD_TYPE` FOREIGN KEY (`FIELD_TYPE_ID`) REFERENCES `field_type` (`FIELD_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `m_form_field_details_ibfk_1` FOREIGN KEY (`TAB_ID`) REFERENCES `tab_table` (`TAB_ID`) ON DELETE CASCADE,
  CONSTRAINT `m_form_field_details_ibfk_2` FOREIGN KEY (`FIELD_SOURCE_LOV_DET_ID`) REFERENCES `list_of_values_details` (`LOV_DET_ID`) ON DELETE SET NULL,
  CONSTRAINT `m_form_field_details_ibfk_3` FOREIGN KEY (`FIELD_SIZE_LOV_DET_ID`) REFERENCES `list_of_values_details` (`LOV_DET_ID`) ON DELETE SET NULL,
  CONSTRAINT `m_form_field_details_ibfk_4` FOREIGN KEY (`FIELD_ICON_LOV_DET_ID`) REFERENCES `list_of_values_details` (`LOV_DET_ID`) ON DELETE SET NULL,
  CONSTRAINT `m_form_field_details_ibfk_5` FOREIGN KEY (`FIELD_ORDER_LOV_DET_ID`) REFERENCES `list_of_values_details` (`LOV_DET_ID`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci