CREATE DATABASE C2C;
USE C2C;

CREATE TABLE DCS_M_PROJECT (
    PROJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    Language_ID INT NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser VARCHAR(100) NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL
) ENGINE=InnoDB;


CREATE TABLE DCS_M_MODULE (
    MODULE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    MODULE_DES VARCHAR(255) NULL,
    MODULE_NAME VARCHAR(255) NOT NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser VARCHAR(100) NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_LANGUAGE (
    Language_ID INT AUTO_INCREMENT PRIMARY KEY,
    Language_Name VARCHAR(50) NOT NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NOT NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL
) ENGINE=InnoDB;

CREATE TABLE DCS_M_DB_CONNECTION (
    DB_CONNECTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    DB_NAME TEXT NULL,
    SERVER_NAME VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PROJECT_ID INT NOT NULL,
    COMPANY_NAME VARCHAR(255) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser VARCHAR(100) NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_CODE_SNIPPET (
    Code_Snippet_ID INT AUTO_INCREMENT PRIMARY KEY,
    Code_Snippet_Name TEXT NULL,
    Snippet TEXT NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    Language_VSP_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE DCS_L_CODE_SNIPPET_LANGUAGE (
    Code_Snippet_Language_ID INT AUTO_INCREMENT PRIMARY KEY,
    Code_Snippet_ID INT NULL,
    Language_ID INT NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser VARCHAR(100) NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NOT NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Code_Snippet_ID) REFERENCES DCS_M_CODE_SNIPPET(Code_Snippet_ID),
    FOREIGN KEY (Language_ID) REFERENCES DCS_M_LANGUAGE(Language_ID)
) ENGINE=InnoDB;

CREATE TABLE DCS_L_USER_PROJECT (
    User_Project_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NULL,
    Project_ID INT NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER VARCHAR(100) NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;

CREATE TABLE DCS_M_AREA (
    Area_ID INT AUTO_INCREMENT PRIMARY KEY,
    Area_Code VARCHAR(50) NULL,
    Area_Name VARCHAR(100) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser DECIMAL(10, 0) NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(20) NULL
) ENGINE=InnoDB;


CREATE TABLE DCS_M_CLASS_PROPERTY (
    Class_Property_ID INT AUTO_INCREMENT PRIMARY KEY,
    Project_ID INT NULL,
    Class_Property_Name VARCHAR(100) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;

CREATE TABLE DCS_M_DAL_SOLUTION (
    DAL_Solution_ID INT AUTO_INCREMENT PRIMARY KEY,
    Project_ID INT NULL,
    DAL_Solution_Name VARCHAR(100) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;

CREATE TABLE DCS_M_DATASOURCE_ACTION_RESULT (
    DATASOURCE_ACTION_RESULT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATASOURCE_ACTION_RESULT_NAME VARCHAR(255) NULL,
    PROJECT_ID INT NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser VARCHAR(100) NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;

CREATE TABLE DCS_M_DATASOURCE_AREA_NAME (
    DATASOURCE_AREA_NAME_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATASOURCE_AREA_NAME VARCHAR(255) NULL,
    PROJECT_ID INT NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser VARCHAR(100) NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_DATASOURCE_CONTROLLER (
     DATASOURCE_CONTROLLER_ID INT AUTO_INCREMENT PRIMARY KEY,
     DATASOURCE_CONTROLLER_NAME VARCHAR(255) NULL,
     PROJECT_ID INT,
     C2C_Cdate DATETIME NULL,
     C2C_Cuser VARCHAR(100) NULL,
     C2C_Udate DATETIME NULL,
     C2C_Uuser INT NULL,
     C2C_Status BOOLEAN NULL,
     C2C_Inactive_Reason VARCHAR(500) NULL,
     FOREIGN KEY (PROJECT_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_FIELD_TYPE (
	 FIELD_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
     FIELD_NAME VARCHAR(255) NOT NULL,
     C2C_Cdate DATETIME NULL,
     C2C_Cuser VARCHAR(100) NULL,
     C2C_Udate DATETIME NULL,
     C2C_Uuser INT NULL,
     C2C_Status BOOLEAN NULL,
     C2C_Inactive_Reason VARCHAR(500) NULL
) ENGINE=InnoDB;


-- DCS_M_LAYOUT
CREATE TABLE DCS_M_LAYOUT (
    Layout_ID INT AUTO_INCREMENT PRIMARY KEY,
    Project_ID INT NULL,
    Layout_Name VARCHAR(100) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;

-- DCS_M_PRODUCT
CREATE TABLE DCS_M_PRODUCT (
    Product_ID INT AUTO_INCREMENT PRIMARY KEY,
    Project_ID INT NULL,
    Product_Name VARCHAR(100) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;

-- DCS_M_VALIDATION
CREATE TABLE DCS_M_VALIDATION (
    Validation_Type_ID INT AUTO_INCREMENT PRIMARY KEY,
    Validation_Name VARCHAR(200) NULL,
    C2C_Cdate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_Udate DATETIME NULL,
    C2C_Uuser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL
) ENGINE=InnoDB;

-- DC_L_Form_Edit_Pagetool
CREATE TABLE DC_L_Form_Edit_Pagetool (
    Form_Edit_Pagetool_ID INT AUTO_INCREMENT PRIMARY KEY,
    Project_ID INT NOT NULL,
    Page_Purpose_ID INT NOT NULL,
    Page_Class_Property VARCHAR(50) NULL,
    Page_DAL_Solution VARCHAR(50) NULL,
    Tab_Name VARCHAR(50) NULL,
    Tab_Layout VARCHAR(50) NULL,
    Save_Clear_Btn BOOLEAN NULL,
    SP_Name VARCHAR(50) NULL,
    C2C_CDate DATETIME NULL,
    C2C_CUser INT NULL,
    C2C_UDate DATETIME NULL,
    C2C_UUser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(50) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;


CREATE TABLE DC_L_Form_Edit_SP_Details (
    Form_Edit_SP_Details_ID INT AUTO_INCREMENT PRIMARY KEY,
    Form_Edit_Pagetool_ID INT NOT NULL,
    SP_Name VARCHAR(100) NULL,
    Column_Name VARCHAR(100) NULL,
    Control_Type VARCHAR(50) NULL,
    Is_Hidden BOOLEAN NULL,
    Field_Order INT NULL,
    Label_Icon VARCHAR(100) NULL,
    Editor_Width INT NULL,
    Data_Source BOOLEAN NULL,
    Area_Name VARCHAR(100) NULL,
    Controller_Name VARCHAR(100) NULL,
    Action_Result VARCHAR(100) NULL,
    List_Name VARCHAR(100) NULL,
    Valueset_Name VARCHAR(100) NULL,
    On_Select BOOLEAN NULL,
    On_Change BOOLEAN NULL,
    Getvalue_Name VARCHAR(100) NULL,
    Contr_Name VARCHAR(100) NULL,
    Placeholder VARCHAR(200) NULL,
    C2C_CDate DATETIME NULL,
    C2C_Cuser INT NULL,
    C2C_UDate DATETIME NULL,
    C2C_UUser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Form_Edit_Pagetool_ID) REFERENCES DC_L_Form_Edit_Pagetool(Form_Edit_Pagetool_ID)
) ENGINE=InnoDB;


CREATE TABLE DC_L_Form_Edit_Validation (
    Form_Edit_Validation_ID INT AUTO_INCREMENT PRIMARY KEY,
    Form_Edit_SP_Details_ID INT NOT NULL,
    Validation_Type_ID INT NOT NULL,
    C2C_CDate DATETIME NULL,
    C2C_CUser INT NULL,
    C2C_UDate DATETIME NULL,
    C2C_UUser INT NULL,
    C2C_Status BOOLEAN NULL,
    C2C_Inactive_Reason VARCHAR(500) NULL,
    FOREIGN KEY (Form_Edit_SP_Details_ID) REFERENCES DC_L_Form_Edit_SP_Details(Form_Edit_SP_Details_ID),
    FOREIGN KEY (Validation_Type_ID) REFERENCES DCS_M_VALIDATION(Validation_Type_ID)
) ENGINE=InnoDB;


CREATE TABLE DC_T_HISTORY_TABLE (
    DC_HISTORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    DB_CONNECTION_ID INT NOT NULL,
    PROJECT_ID INT NOT NULL,
    MODULE_ID INT NOT NULL,
    User_ID INT NOT NULL,
    Page_Name VARCHAR(255) NOT NULL,
    Purpose VARCHAR(500) NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER VARCHAR(100) NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL
    -- Foreign keys can be added if relevant tables exist (DB_CONNECTION, MODULE, PROJECT, USER)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_FORM_EVENT_DETAILS (
    Form_Event_Details_ID INT AUTO_INCREMENT PRIMARY KEY,
    Form_Gen_Details_Id INT NULL,
    Form_Event_VSP_ID VARCHAR(100) NULL,
    Form_Event_Function_Name VARCHAR(100) NULL,
    Form_Gen_Field_Details_ID INT NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Form_Gen_Details_Id) REFERENCES DCS_M_FORM_GENERATION_DETAILS(Form_Gen_Details_Id)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_FORM_FIELD_DETAILS (
    Form_Gen_Field_Details_Id INT AUTO_INCREMENT PRIMARY KEY,
    Form_Gen_Details_Id INT NULL,
    Form_Tab_Name_ID INT NULL,
    Form_Section_ID INT NULL,
    Form_Pop_Up BOOLEAN NULL,
    Form_Gen_Type_VSP_ID VARCHAR(100) NULL,
    Form_Gen_Field_Source_VSP_ID INT NULL,
    Form_Gen_Stored_Procedure VARCHAR(100) NULL,
    Form_Gen_Table_Name VARCHAR(100) NULL,
    Form_Gen_Custom_Field VARCHAR(100) NULL,
    Form_Gen_Column_Name VARCHAR(100) NULL,
    Form_Gen_Alias_Name VARCHAR(100) NULL,
    Form_Gen_Field_Type_ID INT NULL,
    Form_Gen_Validation_ID INT NULL,
    Form_Gen_Field_Size_VSP_ID INT NULL,
    Form_Gen_Field_Icon_VSP_ID INT NULL,
    Form_Gen_Event_Switch BOOLEAN NULL,
    Form_Gen_Event_Switch_ID INT NULL,
    Form_Gen_PlaceHolder VARCHAR(100) NULL,
    Form_Gen_Field_Order_VSP_ID INT NULL,
    Form_Gen_DateSource BOOLEAN NULL,
    Form_Gen_Area_ID INT NULL,
    Form_Gen_Controller_ID INT NULL,
    Form_Gen_Action_ID INT NULL,
    Form_Gen_List_Name VARCHAR(100) NULL,
    Form_Gen_ValueSet_Name VARCHAR(100) NULL,
    Form_Gen_Save_Clear_VSP_ID INT NULL,
    Form_Gen_Field_Hidden BOOLEAN NULL,
    Form_Gen_Grid_Hidden BOOLEAN NULL,
    Form_Gen_Grid_Filterable BOOLEAN NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Form_Gen_Details_Id) REFERENCES DCS_M_FORM_GENERATION_DETAILS(Form_Gen_Details_Id)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_FORM_GENERATION_DETAILS (
    Form_Gen_Details_Id INT AUTO_INCREMENT PRIMARY KEY,
    Form_Tab_Name_Id INT NULL,
    Project_ID INT NULL,
    Module_ID INT NULL,
    Class_Property_ID INT NULL,
    DAL_Solution_ID INT NULL,
    Layout_ID INT NULL,
    Product_ID INT NULL,
    Page_Name VARCHAR(100) NULL,
    Purpose VARCHAR(100) NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Project_ID) REFERENCES DCS_M_PROJECT(PROJECT_ID)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_FORM_SP_NAME (
    Form_Sp_Name_ID INT AUTO_INCREMENT PRIMARY KEY,
    Form_Gen_Details_Id INT NULL,
    Form_Sp_Name VARCHAR(100) NULL,
    Form_Gen_Field_Details_ID INT NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Form_Gen_Details_Id) REFERENCES DCS_M_FORM_GENERATION_DETAILS(Form_Gen_Details_Id)
) ENGINE=InnoDB;


CREATE TABLE DCS_M_FORM_TAB_NAME (
    Form_Tab_Name_ID INT AUTO_INCREMENT PRIMARY KEY,
    Form_Gen_Details_Id INT NULL,
    Form_Tab_Name VARCHAR(100) NULL,
    Form_Tab_Icon_ID VARCHAR(50) NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Form_Gen_Details_Id) REFERENCES DCS_M_FORM_GENERATION_DETAILS(Form_Gen_Details_Id)
) ENGINE=InnoDB;

CREATE TABLE DCS_M_FORM_VALIDATION_DETAILS (
    Form_Gen_Validation_Details_Id INT AUTO_INCREMENT PRIMARY KEY,
    Form_Gen_Details_Id INT NULL,
    Form_Validation_ID INT NULL,
    Form_Gen_Field_Details_ID INT NULL,
    C2C_CDATE DATETIME NULL,
    C2C_CUSER INT NULL,
    C2C_UDATE DATETIME NULL,
    C2C_UUSER INT NULL,
    C2C_STATUS BOOLEAN NULL,
    C2C_INACTIVE_REASON VARCHAR(500) NULL,
    FOREIGN KEY (Form_Gen_Details_Id) REFERENCES DCS_M_FORM_GENERATION_DETAILS(Form_Gen_Details_Id),
    FOREIGN KEY (Form_Validation_ID) REFERENCES DCS_M_VALIDATION(Validation_Type_ID),
    FOREIGN KEY (Form_Gen_Field_Details_ID) REFERENCES DCS_M_FORM_FIELD_DETAILS(Form_Gen_Field_Details_Id)
) ENGINE=InnoDB;


     

